repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        additional_dependencies: []
        files: PR_Dectector/archivos_programa/.*
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: PR_Dectector/archivos_programa/.*
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        files: PR_Dectector/archivos_programa/.*